version: '3'
services:

  sockets:
    build:
      context: ./socket-server
    ports:
      - 3000:3000
    restart: always

  client:
    build:
      context: .
    ports:
      - 5173:5173
    depends_on:
      - sockets
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    networks:
      - outbuild-frontend-kanban
    environment:
      - NODE_ENV=${NODE_ENV}

networks:
  outbuild-frontend-kanban:
    driver: bridge
